### ISSUE TITLE
很喜欢你的文章！！

### ISSUE THREAD

**Issue by huangnuonan** [NervJS/taro-plugin-platform-lark#18]
hi～我是飞书开发者广场的运营同学，之前看到你这篇文章想法很不错，正好我们广场在做征稿活动，想问问能不能收录你的文章呀～

**Comment by liqinuo** [comment]
> hi～我是飞书开发者广场的运营同学，之前看到你这篇文章想法很不错，正好我们广场在做征稿活动，想问问能不能收录你的文章呀～

同学你好，请问你是觉得哪篇文章不错呢？

**Comment by huangnuonan** [comment]
https://github.com/NervJS/taro-plugin-platform-lark 忘了加链接哈哈 这篇

**Comment by liqinuo** [comment]
> https://github.com/NervJS/taro-plugin-platform-lark 忘了加链接哈哈 这篇

严格意义上来说这只是一个开发说明文档，如果你们是有 Taro 开发相关专题或文章需要，收录进去没有问题的
